- args/args.go
- args/json.go
- cache/cache.go
- cache/global.go
- jmx/jmx.go
- log/log.go
- metric/metrics.go
- sdk/data.go
Just some minor improvements in our documentation
> Improve documentation

- docs/tutorial-code/redis.go
- docs/tutorial.md
When going through the tutorial there were some formatting issues and a few
steps that were not immediately apparent to a Go novice.
Fixes those; hope it will improve the tutorial a tiny bit.
Signed-off-by: Nathan L Smith <smith@nlsmith.com>
> Tutorial formatting and clarifications

- sdk/protocol2.go
- sdk/protocol2_test.go
This PR is a first attempt on supporting integrations protocol version 2.
> Added protocol version 2 support

- sdk/protocol2.go
- sdk/protocol2_test.go
In order to keep consistency and provide a solid API, we want to show an empty json object for missing entity.
> Entity as empty json object on marshaling.

- CHANGELOG.md
Updating the CHANGELOG file with the recent changes.
> Updated CHANGELOG with latest unreleased changes

- CHANGELOG.md
- log/log.go
- log/log_test.go
The purpose of this change is allowing to create loggers already configured. Also allowing already created loggers to be configured.
> Allowing Log package to create a logger and configure already created one.

- log/log_test.go
This code fixes the logrus package import path after updating to `v1.*`.
> Fix logrus package after updating to v1.*

- CHANGELOG.md
- sdk/data.go
- sdk/data_test.go
- sdk/protocol2.go
- sdk/protocol2_test.go
> Adding support for events for remote entity

- .travis.yml
- README.md
- args/args_test.go
In order to assure continuous integration we decided to use travis CI. This is first and very basic version.
/cc @mariomac, @smoya
> Adding basic travis config file

- args/args.go
- args/json.go
- cache/cache.go
- docs/tutorial-code/redis.go
- jmx/jmx.go
- log/log.go
- metric/metrics.go
- sdk/data.go
- added -f prefix to log.go methods
- errors start now in lowercase, as recommended by Go nitpicks
> Minor logging corrections

- cache/cache.go
- cache/cache_test.go
- metric/metrics.go
- metric/metrics_test.go
- sdk/v1/data_test.go
- sdk/v2/data_test.go
> Moar linting

- .gometalinter.json
- Makefile
- args/args.go
- args/json.go
- cache/cache.go
- docs/tutorial-code/redis.go
- jmx/jmx.go
- log/log.go
- metric/metrics.go
- metric/metrics_test.go
- sdk/v1/data.go
- sdk/v1/data_test.go
- sdk/v2/data.go
- sdk/v2/data_test.go
Added gometalinter.v2 and fixed lints.
**Please notice**: before merging this branch, we need to change the base to `master` instead of `mmacias/removepointers`.
> Added gometalinter.v2 and fixed lints

- .gometalinter.json
- Makefile
- args/args.go
- args/json.go
- cache/cache.go
- cache/cache_test.go
- docs/tutorial-code/redis.go
- jmx/jmx.go
- log/log.go
- metric/metrics.go
- metric/metrics_test.go
- sdk/v1/data.go
- sdk/v1/data_test.go
- sdk/v2/data.go
- sdk/v2/data_test.go
* Removed redundant pointers.
* Removed ugly "Protocol2" suffixes.
* Added tests to check that the multi-entity events work as expected.
* Deprecated `v1` integration.
** Please notice ** : base for this PR is branch `mmacias/sdkv1v2`. As soon as the mentioned branch is merged, please change the base of this PR to `master`.
> Renaming and tests integration v2 events

- CHANGELOG.md
- args/json.go
- sdk/v2/data.go
Updated changelog with latest breaking change about dividing `sdk` package into `v1` and `v2`.
> Updated changelog with latest breaking change

- Makefile
Supress Make echoes to avoid noisy cli output.
Detailed steps should be at least optional, not mandatory, we just need to know when something goes wrong.
> Supress make echoes

- Makefile
- log/log.go
- log/log_test.go
- persist/global.go
- sdk/v2/data.go
Add verification target to default make and fixed lints.
> Add linting to default make and fixed lints

- CHANGELOG.md
Includes the missing `v2.1.0` release changes in the CHANGELOG.
> Updated CHANGELOG with 2.1.0 release CHANGELOG 

- integration/entity.go
- integration/entity_test.go
- integration/integration.go
- metric/event_test.go
- metric/inventory_test.go
- metric/metrics.go
- metric/metrics_test.go
Increase test coverage
+
Privatize newEntity
> Increase test coverage

- integration/entity.go
- integration/entity_test.go
- integration/integration.go
- metric/event_test.go
- metric/inventory_test.go
- metric/metrics.go
- metric/metrics_test.go
Increase test coverage
+
Privatize newEntity
> Increase test coverage + privatize newEntity

- CHANGELOG.md
Changelog for version 3.0.0-beta
> Changelog v3

- README.md
Document agent-protocol compatibility
> Doc protocol compatibility

- docs/tutorial-code/redis.go
Upgrade tutorial from obsolete sdkv2 to sdkv3.
This fixes the error on `go get` trying to fetch v1 dependencies.
> Remove tutorial obsolete v1 dep

- .travis.yml
Add go 1.10 version to our travis build.
> Add go 1.10 version

- docs/tutorial.md
Improve tutorial to explain how to declare arguments.
- [] assign at least one reviewer
> Exmplain how to declare arguments

- data/metric/metrics.go
- data/metric/metrics_test.go
- integration/options_test.go
- persist/storer.go
- persist/storer_test.go
Storer now supports storing all types of data, not just floats.
> Store all types

- data/inventory/inventory.go
- docs/tutorial.md
- integration/entity.go
> Fix tutorial confusing parts

- docs/tutorial.md
explain how to use DefaultArgumentList.
> explain how to use DefaultArgumentList.

- docs/tutorial.md
Tutorial best-practices section.
> Best practices

- README.md
> Doc on remote entities

- args/args_test.go
> Restore skipped args tests

- data/metric/metrics.go
- data/metric/metrics_test.go
> Convert Gauge to float

- args/args.go
- http/client.go
- http/client_test.go
Create wrapper to ease the task of creating a http client with custom certs.
> Http client wrapper

- data/inventory/inventory.go
- data/inventory/inventory_test.go
- docs/tutorial-code/redis.go
- integration/entity.go
- integration/entity_test.go
- integration/integration_test.go
> Limit inventory key length

- args/args_test.go
Test default arguments with pretty flag and no struct embedding
> Test default arguments without struct embedding

- docs/toolset/README.md
- docs/toolset/http.md
- http/client.go
It also fixes a small error on the http libraries, which multiplies the passed duration by 10^9.
> Documented http helper library

- docs/toolset/README.md
- docs/toolset/jmx.md
> Documented JMX library

- args/args.go
- args/args_test.go
- docs/toolset/examples/persist.go
- docs/tutorial-code/redis.go
- docs/tutorial.md
- integration/integration_test.go
> Remove All flag

- README.md
- docs/toolset/args.md
> Documented arguments' API

- docs/toolset/README.md
> Fixed documentation link

- docs/v2tov3.md
Add steps to ease the migration from `v2` to `v3`
> Add steps to migrate from v2 to v3

- docs/tutorial-code/single-entity/redis.go
- docs/tutorial.md
Improve tutorial documentation.
Delete misleading comments when creating LocalEntity and use arguments so it's clear why they are useful.
> Delete misleading comment + use arguments

- jmx/jmx.go
Reduce JMX memory allocation by shrinking the channel buffer
> Reduce JMX memory allocation

- data/metric/metrics.go
- data/metric/metrics_test.go
- docs/tutorial-code/multiple-entities/redis-multi.go
- docs/tutorial-code/single-entity/redis.go
- integration/entity.go
- integration/integration_test.go
Remove obsolete constructor returned errors
> Remove obsolete returned errors

- .gometalinter.json
- Makefile
- args/json.go
- persist/storer.go
> Remove TODOs

- .gometalinter.json
- Makefile
- args/json.go
- log/log.go
- persist/storer.go
- Fixes log prefix (log-level + time)
- Removes *deprecated* comments on global logger
> Fix log prefix

- CHANGELOG.md
> Changelog 3.0.1

- docs/toolset/integration.md
Fixes an error in one of the examples
> Fix example error

- README.md
> Fix readme go get

- docs/toolset/integration.md
Update doc to target RATE & DELTA required attribute/s
> Doc for RATE & DELTA required attribute/s

- jmx/jmx.go
> Fix JMX flush warnings

- jmx/jmx.go
> Fix JMX race on wait

- data/metric/set_marshal_test.go
Metric marshal improve readability.
> Metric marshal readability

- data/metric/metrics.go
- data/metric/set_marshal.go
- data/metric/set_marshal_test.go
- data/metric/source_type.go
- data/metric/source_type_test.go
Metric sources mapping btw name & type.
> Metric sources mapping btw name & type

- persist/storer.go
Use locker to syncronize inMemory store object.
> Add locker to inmemorystore

- persist/storer.go
Fixes recently added Store lock
> Fix store lock

- args/args.go
- data/metric/metrics.go
- integration/entity.go
- integration/integration.go
Add a way using environment variables with a specific prefix to decorate samples with custom attributes.
> add custom attributes

- args/args.go
- args/args_test.go
- integration/integration.go
> Rrename -custom_attributes flag to -metadata

- .gometalinter.json
- Makefile
- README.md
- args/args_test.go
- args/json.go
- cache/cache.go
- cache/cache_test.go
- docs/tutorial-code/redis.go
- docs/tutorial.md
- jmx/jmx_test.go
- log/log.go
- metric/metrics.go
- metric/metrics_test.go
- sdk/data.go
- sdk/data_test.go
Fix SDK v2 dependencies, as master is now targeting v3.
> Fix SDK v2 dependencies

- docs/v2tov3.md
> toolset link

- Makefile
> Fix golint

- docs/v2tov3.md
Add note about the removal of `NRIA_CACHE_PATH` on v3
> Add note about NRIA_CACHE_PATH removal

- .travis.yml
Skip Go 1.7 and 1.8 on Travis, until we can skip golint on those
> Skip Go 1.7 and 1.8 on Travis, until we can skip golint on those

- integration/integration_test.go
- integration/options_test.go
> Unescape test output

- README.md
> Link to official wire protocol doc

- docs/entity-definition.md
- docs/toolset/args.md
> Document custom metadata decoration args

- CONTRIBUTING.md
Minor improvement in our CONTRIBUTING guideline.
> Fix copy-paste mistake in CONTRIBUTING file

- jmx/jmx.go
- jmx/jmx_test.go
Refactor: remove duplication on JMX because of SSL
> Refactor: remove duplication on JMX

- README.md
- jmx/jmx.go
- jmx/jmx_test.go
See:
- https://github.com/newrelic/infra-integrations-sdk/pull/163
- https://github.com/newrelic/nrjmx/pull/11
- https://github.com/newrelic/nri-jmx/pull/33
> SSL support for JMX

- integration/entity.go
- integration/entity_test.go
- integration/integration.go
Remove functional options from entity constructor
> Remove func opts from entity

- integration/entity.go
- integration/entity_test.go
- integration/integration.go
- integration/integration_test.go
> IHOST-1997 sorted identifier attributes

- integration/entity.go
- integration/entity_test.go
Sorting IDs attributes in agent
> IHOST-1997 removed sorted id attrs

- CHANGELOG.md
- README.md
- docs/entity-definition.md
- docs/protocol-v3.md
> Protocol v3 doc

- docs/protocol-v3.md
> Add agent version that supports loopback replacement

- CHANGELOG.md
- data/metric/metrics.go
- data/metric/metrics_test.go
- data/metric/set_marshal.go
- data/metric/set_marshal_test.go
- data/metric/source_type.go
- data/metric/source_type_test.go
This PR adds unsigned versions of RATE and DELTA, this is driven by the fact that we had a check for non-negative RATE/DELTA then remove it, and now it's being asked again. This adds the flexibility to use both cases.
https://github.com/newrelic/infra-integrations-sdk/pull/110
- [x ] add a risk label after carefully considering the "blast radius" of your changes
- [x ] describe the _intent_ of your changes in the description. don't just rewrite your code in prose
- [x ] assign at least one reviewer
> Add positive versions of rate and delta

- docs/toolset/jmx.md
JMX remote documentation update
> JMX  remote doc update

- LICENSE
> update LICENSE to MIT

- jmx/jmx.go
- jmx/jmx_test.go
jmx no user/password auth connection api
> jmx no-auth connection

- jmx/jmx.go
- jmx/jmx_test.go
Fix `jmx` package error handling & improve logging
*Disclaimer:*
`jmx` package is poorly designed and will be revamped in the future, this is trying to get it working with minimum effort investment.
> Fix JMX logging & error handling

- jmx/jmx.go
> Fix jmx connection URL option

- jmx/jmx.go
JMX add user&pass when using connection URL.
> Not adding changelog conn-URL as still not been released.
> JMX add user&pass when using conn URL

- jmx/jmx.go
JMX improve connection error handling
> JMX improve connection error handling

- data/metric/metrics_test.go
Test showing metric value overwriting behaviour
> Test showing metric value overwriting behaviour

- data/metric/metrics.go
- data/metric/metrics_test.go
- jmx/jmx_test.go
This PR will prevent adding metric non-numeric value that can generate errors while trying to construct the JSON
> Fix json marshal errors

- .gitignore
- .golangci.yml
- .gometalinter.json
- .travis.yml
- CHANGELOG.md
- Makefile
- args/args.go
- args/args_test.go
- data/inventory/inventory.go
- data/inventory/inventory_test.go
- data/metric/metrics_test.go
- docs/tutorial-code/multiple-entities/redis-multi.go
- docs/tutorial-code/single-entity/redis.go
- go.mod
- go.sum
- http/client_test.go
- integration/integration_test.go
- integration/options_test.go
- jmx/jmx.go
- jmx/jmx_test.go
- log/log_test.go
- persist/storer_test.go
Add support for go modules
Fixed linter issues with new more modern linter
> use go modules

- data/metadata/metadata.go
- data/metadata/metadata_test.go
- docs/tutorial-code/multiple-entities/redis-multi.go
- integration/entity.go
- integration/entity_test.go
- integration/integration.go
- integration/integration_test.go
- integration/options_test.go
Rename entity tags to entity metadata
Adding a tag to an entity adds the prefix "tags." to the key.
Add "integration" section to integration
> SDK v4 metadata tags change

- .travis.yml
Removes 1.7
Adds 1.11, 1.12, 1.13, 1.14
> Update Go versions support

- CHANGELOG.md
- README.md
- docs/README.md
- docs/toolset/http.md
- docs/v3_tools_faqs.md
Updates the different README documents for the new SDK v4 to reflect the internal release. This PR doesn't remove all the documentation from previous versions.
> SDK v4 readme update

- docs/tutorial.md
> Updated docs

- data/metric/metrics.go
- data/metric/metrics_test.go
- integration/integration_test.go
This PR will fix the json for prometheus summary and histogram.
> Fix prometheus summary and histogram serialization

- docs/v2tov3.md
As discussed here: https://newrelic.slack.com/archives/C011N67US80/p1626446541273400
And here: https://newrelic.slack.com/archives/C011N67US80/p1626708040278100
> docs: fix some typos in v2tov3

- http/client.go
- http/client_test.go
HTTP Client: Add possibility to skip server verification and refactor client to work with options pattern
> HTTP Client: Add possibility to skip server verification and refactor client to work with options pattern

- docs/v3tov4.md
Adds docs related to common dimensions released [here](https://github.com/newrelic/infra-integrations-sdk/releases/tag/v4.1.0)
> doc: add common dimensions docs

- integration/entity.go
- integration/entity_test.go
- integration/integration_test.go
Align common data with telemetry API: https://github.com/newrelic/newrelic-telemetry-sdk-go/blob/master/telemetry/metrics.go#L241
Infra agent: https://github.com/newrelic/infrastructure-agent/blob/30d0e84f3526ab0e1398d7908cc6e73193a21109/pkg/backend/telemetryapi/metrics_test.go#L52
> fix: entity commondimension aligned with telemetry sdk

- integration/entity.go
- integration/entity_id.go
- integration/entity_test.go
Fix race condition when retrieving an entity at the same time as it's updated
> Fix race condition new metric set

- jmx/jmx.go
- persist/storer.go
- persist/storer_test.go
- Add new TmpPath public function to return a custom tmp path to the given integration's file.
> Add new TmpPath public function

- persist/store_path_test.go
- persist/storer.go
- persist/storer_test.go
- Custom tmp dir doesn't add "nr-integrations" subfolder
> Custom TMP_DIR doesn't add nr-integrations subfolder
