newrelic/infra-integrations-sdk

jmx/jmx.go
jmx/jmx_test.go

Cassandra integration, which uses the JMX package, fails in some cases because some of the queries takes more time than 1s. Due to this we need to have a way to configure the timeout per each query.

[jmx] Adding timeout argument to the Query function

---

jmx/jmx.go

Cassandra integration currently is failing if the customer doesn't specify password and username (so in case when JMX authentication is disable).
As a fix, in the function that composes the command sent to nrjmx tool we ignore password and username if they're empty.

[jmx] Ignore password and username arguments if empty 

---

CHANGELOG.md
log/log.go

This code fixes the logrus version to `v1.*` since is the one we are using. 
This would be a BC for current users if they use an older version.

Updated logrus to v1.*

---

log/log.go
log/log_test.go

Here we downcase import line for logrus to avoid an issue where go get tries to
include a package by the same name, but lowercased and fails.  This comes up as
part of including logrus in another project, where we want to use this SDK and
can't duplicate the logrus package with capitalizing our import.
I think the general case here is to have the package name downcased, even though
github works with either.

Downcase import line for logrus

---

cache/cache.go
cache/cache_test.go
cache/global.go
docs/tutorial-code/redis.go
log/log.go
log/log_test.go
sdk/v1/data.go
sdk/v2/data.go

1. Decouples logger from `logrus` via `interface` extraction and `Writer` injection.
2. Its default implementation uses Go builtin component.
A further refactor on global cache is required to remove `deprecated` `SetDebug(bool)` method.

Decouple logger

---

data/inventory/inventory.go
integration/integration_test.go

This patch fixes the bug that made inventory to not be marshalled into JSON.

Fixed inventory JSON marshaling

---

Makefile
integration/entity.go
integration/integration.go
jmx/jmx.go
jmx/jmx_test.go
persist/storer.go

Fix JMX race conditions:
* locks on data (enables concurrency)
* cancels query context on:
- timeout
- empty query output
If query goroutine is not stopped, it could possible lock the integration in a `defunct` state (orphaned goroutine keeping the `nrjmx` alive).

Fix JMX race conditions

---

data/metric/metrics.go
data/metric/metrics_test.go
integration/integration.go
integration/options_test.go
persist/storer.go
persist/storer_test.go

The old cache implementation didn't allow to unmarshall directly into a custom struct (only to basic types and maps).
This change breaks the previous storer API.

Using a new Storer that allows unmarshalling into structs

---

data/metric/metrics.go
data/metric/metrics_test.go
docs/toolset/README.md
integration/entity.go
persist/storer.go
persist/storer_test.go

Fixes cache collision on the store for _rate&deltas_ when a **same metric name** is used.
Attributes are supported to namespace the metric name on the _NewSet_ constructor.
Fix test at `TestNewSet_Attr_SolvesCacheCollision` https://github.com/newrelic/infra-integrations-sdk/pull/106/files#diff-d41479d78f43948797a5970be862f5e0R196

Cache collision fix

---

CHANGELOG.md
integration/integration.go
integration/integration_test.go

Inside Entity creation there is a loop that checks previous entities' Metadata (Name and Namespace). The problem is that local entities don't have an associate Metadata, so if you create a local entity and then a remote entity a nil pointer crash happens.

Fixed nil pointer when creating an entity

---

integration/integration.go
integration/integration_test.go

Logger now is responsive to the `--verbose` configuration argument.
The patch include unit tests.

Fix debug mode for default logger

---

docs/toolset/log.md
docs/v2tov3.md
integration/integration.go
log/log.go
log/log_test.go

It keeps the public API of the global logger, but changes its internal
implementation to not depend on logrus.
This patch also restores the warning messages.

    Restore and deprecate global logger

---

data/metric/metrics.go
data/metric/set_marshal.go
data/metric/set_marshal_test.go
data/metric/source_type.go
data/metric/source_type_test.go

Metrics marshalling form JSON.
Added `MarshalMetrics` to `metric.Set` as a way to utilize struct field tags to turn struct fields into metrics. The way `MarshalMetrics` works is it recursively traverses a struct until a non-struct/non-pointer value is found. If the field associated with that value has the `metric_name` and `source_type` struct field tags it will pass the value into `SetMetric`. Nil pointers are ignored regardless of the required struct field tags being present. 
Depends on:
- https://github.com/newrelic/infra-integrations-sdk/pull/131
- https://github.com/newrelic/infra-integrations-sdk/pull/132
- https://github.com/newrelic/infra-integrations-sdk/pull/133

Metrics marshall

---

jmx/jmx_test.go

Skip JMX timeout test, because CI runtime is unreliable.

Skip JMX timeout test

---

CHANGELOG.md
args/args.go
args/args_test.go
docs/tutorial-code/single-entity/redis.go

Arguments getters.
To avoid people concatenating `All` conditionals like:
```golang
if args.GlobalArgs.All() || args.GlobalArgs.Inventory {
```
Adds support for:
```golang
if args.GlobalArgs.HasInventory() {
```
On the 3 metric types `HasInventory`, `HasEvents`, `HasMetrics`

Arguments getters

---

integration/entity.go
integration/entity_test.go

Entities require name and type, if empty an error should be returned. Otherwise we'll be using a local-entity under the hood.

Entities require name and type

---

integration/integration.go
integration/integration_test.go
integration/options_test.go

The contract between the agent and integrations is that integrations
would print a single line output. If the execution of the integration
binary returns multiple integration outputs, they have to be separated
by a break line.
You can compare the current behavior with v2.2.0:
https://github.com/newrelic/infra-integrations-sdk/blob/v2.2.0/sdk/data.go#L95
As you can see, in that version we were using `Println()`

Update integration.Publish method to print breaklines

---

CHANGELOG.md
args/args.go
args/args_test.go
docs/entity-definition.md
docs/toolset/args.md
integration/entity.go
integration/entity_test.go
integration/integration.go
integration/integration_test.go

With the move to remote entities, we've impacted our usability by making it difficult to organize integration data.
This solution provides a way to attach meta data that would be useful to provide the best user experience that can be definable from the agent config file, env-var or directly cli-arg to the integration.
- `NRI_CLUSTER` env-var or `-nri_service` cli flag: an optional attribute that could be either stated by the user or set by a developer. Ideally this would be the name for a kafka cluster etc.
- `NRI_SERVICE` env-var or `-nri_service` cli flag: to label services
- `NRI_ADD_HOSTNAME` env-var or `nri_add_hostname` cli flag: for the agent to decorate samples with the hostname

Hostname, Cluster and Service Metadata

---

docs/tutorial.md

During the tutorial I realised that the **integration_name** needs to be in camel case following the golang naming conventions. Otherwise it returns an error when it validates the code with gometalinter.v2.
I added a small comment explaining this.

Added documentation for integration name

---

README.md
jmx/jmx.go
jmx/jmx_test.go

Customer requests to use JMX OHI over SSL. I am adding SSL arguments to the wrapper to nrmjx - the related PR to modify nrjmx is https://github.com/newrelic/nrjmx/pull/11 
- [impacts any OHI using JMX] 
- [Added certs in the environment when making the JMX connect call. nr-jmx wrapper use Jmx.Open in the SDK that needs to be updated for nr-jmx send SSL arguments to nrjmx ]

Adding arguments for SSL option for JMX connect

---

integration/entity.go
integration/entity_test.go
integration/integration_test.go

Moved cluster and service to `EntityMetadata` instead of `Entity`

changed cluster & service in metadata

---

CHANGELOG.md
integration/entity.go
integration/entity_test.go
integration/integration.go
integration/integration_test.go
integration/options_test.go

New protocol version 3. Added `identifier attributes` in Entity metadata in order to have uniqueness in the entity key.

Protocol V3: Added identifier attributes 

---

CHANGELOG.md
docs/toolset/jmx.md
jmx/jmx.go
jmx/jmx_test.go

Added a remote boolean flag for the **NR_JMX_TOOL** for enabling  jmx client in EAP 6.

Added remote jmx flag for jBoss6

---

integration/entity.go
integration/entity_test.go

SDK feature proposal *Attaching attributes to entity*:
There are cases (integrations) where attributes should be added to all the metrics (actually metric-*sets*) of an entity.
Current SDK only allow adding them on a per metric-*set* basis (using `nameSpacingAttributes` https://github.com/newrelic/infra-integrations-sdk/blob/master/integration/entity.go#L98 ). So for every the metric-*set* you have to add them (see https://github.com/newrelic/nri-rabbitmq/blob/master/src/metrics/metrics.go#L59 )

Add entity attributes

---

CHANGELOG.md
data/metric/metrics.go
docs/entity-definition.md
integration/entity.go
integration/entity_id.go
integration/entity_test.go
integration/integration.go
integration/integration_test.go

We may also want to differentiate:
- The host/entity **producing** a remote entity data
- The host/entity **reporting** a remote entity data 
This gets relevance whenever the host reporting remote entity data is not the one producing it.
Usually for clusterised services a host/node entity reports data about the cluster entity. In this case we may want 
to know which entity (host/node) is reporting this cluster-entity data.
To know which entity is reporting current entity data we introduce the `integration.EntityKey` type and new attributes for metrics `reportingEntityKey` and `ReportingEndpoint`.

EntityKey + attributes: ReportingEntityKey & ReportingEndpoint

---

integration/entity.go
integration/entity_test.go
integration/integration.go
integration/integration_test.go

[Identifier attributes](/blob/master/docs/entity-definition.md#identifier-attributes) are a coupled to the entity uniqueness. So different id-attrs should fetch/create different entities.

Entity fetching uses identifier attributes

---

jmx/jmx.go

Sets JMX remote mode ready for JBoss Domain-mode and adds support to enable JBoss Standalone-mode.
Official doc for remoting v3 is not available, see:
- https://developer.jboss.org/thread/196619
- http://jbossremoting.jboss.org/documentation/v3.html
Some doc on URIS at:
- https://github.com/jboss-remoting/jboss-remoting/blob/master/src/main/java/org/jboss/remoting3/EndpointImpl.java#L292-L304
- https://stackoverflow.com/questions/42970921/what-is-http-remoting-protocol
- http://www.mastertheboss.com/jboss-server/jboss-monitoring/using-jconsole-to-monitor-a-remote-wildfly-server.

JMX Remote Domain and Standalone JBoss modes

---

jmx/jmx.go

Add uriPath command line option to support applications that use non-standard JMX service urls such as ForgeRock OpenDJ.
OpenDJ uses a JMX service uri like: service:jmx:rmi:///jndi/rmi://localhost:1689/org.opends.server.protocols.jmx.client-unknown
This pull request depends on enhancements to nrjmx in this pull request: https://github.com/newrelic/nrjmx/pull/19
- [X ] describe the _intent_ of your changes in the description. don't just rewrite your code in prose

Add uriPath option to support ForgeRock OpenDJ

---

CHANGELOG.md
data/event/event.go
data/event/event_test.go
docs/v2tov3.md
integration/integration_test.go

Adds support for event attributes, currently events only support two fields `summary` and `category`, this PR allows us to specify a map of key value attributes for the event.
PENDING:
- [ x] add a risk label after carefully considering the "blast radius" of your changes
- [ x] describe the _intent_ of your changes in the description. don't just rewrite your code in prose
- [ x] assign at least one reviewer

[Waiting for agent release] Add support for event attributes

---

CHANGELOG.md
jmx/jmx.go

Remove JMX lock, as it does not support concurrency by design.
`jmx` package needs a whole re-design, starting by its API.

Remove JMX lock

---

CHANGELOG.md
jmx/jmx.go

JMX: remove line length limitation
Status before this was that `jmx` package was reading `nrjmx` tool stdout and stderr into a limited buffer, so lines that does not fit into that size were silently dropped.
This replaces buffered IO with unlimited stream read IO.

JMX: remove line length limitation

---

jmx/jmx.go

JMX package avoid nrjmx stderr closed error.
While reading from stderr, fd could have been closed by `cmd.Wait`, this is an expected error that doesn't cause any issue. We can safely ignore it.
Going further this error comes from wrong `jmx` package API design, but this will be tackled in the future.

Jmx avoid stderr closed err

---

CHANGELOG.md
jmx/jmx.go
jmx/jmx_test.go

Adds:
- jmx multiline output support.
- remove line length limitation 
Status before:
- only first jmx stdout line was read, but there are cases where nrjmx will write several lines
- jmx package was reading nrjmx tool stdout and stderr into a limited buffer, so lines that does not fit into that size were silently dropped. This replaces buffered IO with unlimited stream read IO.

jmx multiline support

---

CHANGELOG.md
jmx/jmx.go
jmx/jmx_test.go

- JMX package  custom `nrjmx` executable tool option
- JMX package avoid nrjmx stderr closed error.
While reading from stderr, fd could have been closed by cmd.Wait, this is an expected error that doesn't cause any issue. We can safely ignore it.
> Going further this error comes from wrong jmx package API design, but this will be tackled in the future.

JMX: custom nrjmx exec option + remove stderr closed

---

CHANGELOG.md
jmx/jmx.go
jmx/jmx_test.go

1. Added verbose log mode
2. Fixed `jmx` package  warning handling
3. Converted "bean pattern error" from warning to proper error
**2) Detail:**
Previously `nrjmx` warning output was just logged. Then Query waited for cmd timeout returning an error. Now a warning avoids waiting for timeout returning nil and logging on Warning level.
> Once we change jmx pacakge API, this should be modified so Query fn could return proper error/warning types.

Fix jmx warning handling

---

jmx/jmx.go
jmx/jmx_test.go

JMX full connection URL support. So user can avoid using this myriad of arguments being: hostname, port, uri-path, is-remote and so.
Related: https://github.com/newrelic/nrjmx/pull/37

JMX full connection URL

---

jmx/jmx.go

JMX restore auto close on timeout or empty line as on previous releases to avoid BCs.

JMX restore auto close on timeout or empty line

---

jmx/jmx.go

Previously, `doQuery` was only returning when an EOF was encountered.
However, this causes issues when multiple queries are to be sent to the
`nrjmx` process. Multiple `doQuery` goroutines were running at the
same time, and it appears the first one to run was always consuming
stdOut, which caused all remaining queries to fail with a timeout.

Stop reading from stdOut after receiving message

---

CHANGELOG.md
jmx/jmx.go
jmx/jmx_test.go

JMX: restoring `nrjmx` stdout single line ingestion.
This rolls back `nrjmx` stdout multiline support (still not released) to speed up querying, as multiline support seems to be not required.
`nrjmx` stderr ingest multiline is kept as a query error can write several lines into stderr.

JMX restore single nrjmx line ingest

---

CHANGELOG.md
data/attribute/attribute.go
data/attributes/attributes.go
data/event/event.go
data/event/event_test.go
data/metric/metrics.go
data/metric/metrics_test.go
data/metric/set_marshal_test.go
docs/entity-definition.md
integration/entity.go
integration/entity_test.go
integration/integration_test.go

This PR allows events with attributes to be decorated with the entity `customAttributes` when they are added to via the `entity.AddEvent` function.
- [x ] add a risk label after carefully considering the "blast radius" of your changes
- [x ] describe the _intent_ of your changes in the description. don't just rewrite your code in prose
- [x ] assign at least one reviewer
- [x ] document feature

Enable custom attributes for events

---

.gitignore
CHANGELOG.md
log/log.go

Removed panic call when `log.Fatal` is called, in favour of just calling `os.Exit(1)`; the same as the standard Go logging library does.

Removed panic when log.Fatal is called

---

CHANGELOG.md
integration/integration.go
jmx/jmx.go

This PR will fix the issue in the global logger which caused the debug messages to be discarded when verbose mode was enabled.

Fix for the global logger when in verbose mode

---

CHANGELOG.md
jmx/jmx.go

Return jmx client error when nrjmx integration connection failed or process exited. With this change we allow other integration to handle this error type.

Add jmx client error

---

data/metric/metrics.go
data/metric/metrics_test.go
integration/integration_test.go

Nan or Inf values can be passed for summary metrics and will be serialized as null in the json output

feat(metrics): allow NaN and Inf

---

integration/integration.go
integration/integration_test.go

This add support for finding an entity by name. This is required to avoid adding metrics belonging to the same entity in different entity entries (although they would end up being the same entity) and reducing the overall payload

feat(integration): add find entity by name

---

data/metric/metrics.go

While using the nri-haproxy integration I've noticed the rates for connections per second, bytes per second, and other things that were defined as type PRATE were all wrong.  I could manually collect statistics for HAProxy and calculate rates and nothing lined up with what the integration calculated.  On further inspection, I found in the SDK that if a metric was defined as a source type of PRATE, it was not actually having a rate calculated for it.  This PR fixes this problem.  The one line code fix ensures that rates are calculated for a source type of RATE or PRATE.

Fix rates to be calculated for PRATE source types as well

---

data/metric/metrics.go
integration/integration_test.go

The json annotation was wrongly named count. the agent expect the field `value`

fix: Rename value annotation for count metric.

---

integration/entity.go
integration/entity_test.go

Adding support for entity "common" dimensions. These ones are applied to every entity metric at platform level.
I'm not adding documentation for "common dimensions" as we [need to fix what a dimension is](https://github.com/newrelic/infra-integrations-sdk/issues/255).
Fixes https://github.com/newrelic/infra-integrations-sdk/issues/250

feat: entity common dimensions support

---

jmx/jmx.go
jmx/jmx_test.go
log/log.go

Problem: when SDK receives any warning from NRJMX integration, it stops to process remaining data. It has race condition inside, so sometimes it will process data first and exits, in some cases it will print warning first and exits.
Solution: make warning processing not terminating case (remove return from warning case) and add all warnings processing function to call as a defer for all return cases. This will help us with behaviour consistency
Chore: add SetOutput function for a logger, to be able to replace output stream for tests

fix: warning stops mbeans processing

---

jmx/jmx.go
jmx/jmx_test.go
jmx/jmx_unix.go
jmx/jmx_windows.go
log/log.go

I have created a v3 branch that should be used to track all patches and tag the following versions of the SDK v3.X
This PR adds:
* Cherry picked commit e4dedaa
* Add lastest fixes on v4 786cf26 on the jmx package
After review-merge of this PR to v3 we should that branch with `v3.6.6` release and that Fixes #261

Add jmx package fixes to v3 branch

---

data/metric/metrics.go
data/metric/metrics_test.go
integration/entity.go
integration/entity_id.go
integration/integration.go
integration/integration_test.go
integration/options_test.go
persist/store_path.go
persist/store_path_test.go
persist/storer.go

This PR will:
- add unique ID for integration instance based on integration cmd line arguments
- use the unique ID when creating the file for rate/delta storage (this will avoid collision issues when using discovery)
- add entityKey as a namespace attribute to the metric set

feat: add unique path for storage file

---

jmx/jmx.go
jmx/jmx_test.go

- add host and port getters so can be retrieved in the integrations when a connection query fails

Add JMX host and port getters so can be retrieved in the integrations when a connection query fails

---

persist/storer.go
persist/storer_test.go

Adds a garbage collect mechanism to remove entries from the storer file saved on disk which has been expired.
Expiration is calculated using the same `TTL`  that is being used to remove storer files and the mechanism remove the entires that has not been updated in a period greater than the `TTL`
Fixes #294 
**Context for the reviewer**:
- Storer files are created one per instance of the integration running on the host, since a hash, computed from the args, is [added to the file name](https://github.com/newrelic/infra-integrations-sdk/blob/v3/integration/integration.go#L103).
- Entries on the storer file are identified by the metric set attributes, usually entity attributes.
- The [current mechanism ](https://github.com/newrelic/infra-integrations-sdk/blob/v3/persist/store_path.go#L59)remov …

feat(persist): clean old entries upon loading store file

---

Makefile
args/args.go
docs/tutorial-code-v3/multiple-entities/redis.go
docs/tutorial-code-v3/single-entity/redis.go
integration/integration_test.go
jmx/jmx.go
jmx/jmx_test.go
jmx/jmx_unix.go

Fix JMX nil pointer

---

persist/storer.go

There a some integrations ([apache](https://github.com/newrelic/nri-apache/pull/132),  [cassandra](https://github.com/newrelic/nri-cassandra/pull/205), [nginx](https://github.com/newrelic/nri-nginx/pull/161), ...) that had a custom storer implementation.
This PR honors back that legacy behavior ins case there is any customer using that feature.

Honor storer envvar (NR-302384)
